apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: longhorn.iot.keutgens.be
  dnsNames:
    - longhorn.iot.keutgens.be
  duration: 8760h
  renewBefore: 360h
