apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-timescale-pvc
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
  volumeName: postgre-data
