apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: postgresql
type: Opaque
stringData:
  POSTGRES_USER: administrator       # <--- Change with your username
  POSTGRES_PASSWORD: **********      # <--- Change with your password
  POSTGRES_DB: postgres
