apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-pvc-layout
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - >
              mkdir -p /mnt/conf /mnt/providers /mnt/themes;
              chown -R 1000:1000 /mnt 2>/dev/null || true;
              echo "init done";
          volumeMounts:
            - name: keycloak-data
              mountPath: /mnt
      containers:
        - name: keycloak
          # image die --auto-build ondersteunt
          image: quay.io/keycloak/keycloak:22.0.5
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start", "--auto-build"]
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: keycloak-secret
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: timescaledb.postgresql.svc.cluster.local
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_PROXY
              value: edge
            - name: KC_PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: /
            - name: KC_HOSTNAME
              value: keycloak.iot.keutgens.be
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/conf
              subPath: conf
            - name: keycloak-data
              mountPath: /opt/keycloak/providers
              subPath: providers
            - name: keycloak-data
              mountPath: /opt/keycloak/themes
              subPath: themes
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              httpHeaders:
                - name: Host
                  value: keycloak.iot.keutgens.be
            initialDelaySeconds: 300
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              httpHeaders:
                - name: Host
                  value: keycloak.iot.keutgens.be
            initialDelaySeconds: 600
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
