apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
stringData:
  KC_DB_USERNAME: keycloak_user
  KC_DB_PASSWORD: ********                # Edit password
  KEYCLOAK_ADMIN: iotadmin
  KEYCLOAK_ADMIN_PASSWORD: *********      # Edit password
