apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom-config
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      hosts {
        192.168.50.210 kubedash.iot.keutgens.be
        192.168.50.210 grafana.iot.keutgens.be
        192.168.50.210 longhorn.iot.keutgens.be
        192.168.50.210 keycloak.iot.keutgens.be
        fallthrough
      }
      forward . 8.8.8.8
      log
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-custom
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coredns-custom
  template:
    metadata:
      labels:
        app: coredns-custom
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - coredns-custom
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: coredns
        image: coredns/coredns:latest
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
      volumes:
      - name: config-volume
        configMap:
          name: coredns-custom-config
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-custom
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: lb-pool
spec:
  type: LoadBalancer
  selector:
    app: coredns-custom
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: tcp-udp
    protocol: TCP
    port: 53
    targetPort: 53
